readme: >
  - YOLO imags need to be in a tree like detection -> tiles,wsi -> train,val,test -> images,labels
  - cnn_data_root doesn't need to exist, will be created a tree like: 
    cnn_dataset -> train,val,test -> class0,class1,class2.. ->
  - weights_path: path to the downloaded the VGG16 checkpoint file
  - cnn_exp_fold: desired location to store results from cnn experiments. Doesn't need to exist already.

  REQUIREMENTS: 
  detect.py in yolo should be changed here: 
    1) for j, (*xyxy, conf, cls) in enumerate(reversed(det)):
    ...
    2) save_one_box(xyxy, imc, file=save_dir / 'crops' / names[c] / f'{p.stem}_crop{j}.jpg', BGR=True)

    muw classes: {'Glo-unhealthy':0, 'Glo-NA':1, 'Glo-healthy':2, 'Tissue':3},


##################################################
#############    CNN_TRAINER.PY    #############
##################################################
cnn_trainer:
  {
    yolo_data_root: '/Users/marco/helical_tests/test_cnn_zaneta/detection',
    cnn_data_root: '/Users/marco/helical_tests/test_cnn_zaneta',
    map_classes: {'Glo-healthy':0, 'Glo-unhealthy':1, 'false_positives':2},
    yolo_exp_folds: [ '/Users/marco/helical_tests/test_cnn_zaneta/exp42','/Users/marco/helical_tests/test_cnn_zaneta/exp43'], # exp30=test
    lr: 0.001,
    k_tot: 4,
    k_i: 2,
    batch: 5,
    epochs: 2,
    num_workers: 0,
    weights_path: '/Users/marco/.cache/torch/hub/checkpoints/vgg16_bn-6c64b313.pth',
    cnn_exp_fold: '/Users/marco/helical_tests/cnn_model/exps',
    dataset: 'muw',
    task: 'detection',
    resize_crops: True,
    treat_as_single_class: False,
    device: 'mps'
  }
##################################################


##################################################
#############    CNN FEATURE EXTRACTOR.PY    #############
##################################################
cnn_feature_extractor:
  {
    cnn_root_fold: '/Users/marco/helical_tests/test_cnn_zaneta',
    # cnn_data_root: '/Users/marco/helical_tests/test_cnn_trainer',
    map_classes: {'Glo-healthy':0, 'Glo-unhealthy':1, 'false_positives':2},
    # yolo_exp_folds: ['/Users/marco/helical_tests/test_cnn_trainer/exp10', '/Users/marco/helical_tests/test_cnn_trainer/exp11','/Users/marco/helical_tests/test_cnn_trainer/exp12'], 
    vgg_weights_path:  '/Users/marco/.cache/torch/hub/checkpoints/vgg16_bn-6c64b313.pth',
    cnn_weights_path: '/Users/marco/Downloads/VGG16_v2-OCT_Retina_half_dataset.pt',
    yolo_root: '/Users/marco/helical_tests/test_cnn_zaneta/detection',
    exp_folds: ['/Users/marco/helical_tests/test_cnn_zaneta/exp42', '/Users/marco/helical_tests/test_cnn_zaneta/exp43'],
    num_workers: 1,
    resize_crops: True
  }
##################################################

##################################################
#############    MIL_RUNNER_TRUE.PY    #############
##################################################
mil_trainer:
  {
    root: '/Users/marco/helical_tests/test_cnn_zaneta/cnn_dataset',
    all_slides_dir: '/Users/marco/Downloads/zaneta_files/safe',
    map_classes: {'Glo-healthy':0, 'Glo-unhealthy':1, 'false_positives':2},
    bag_classes:  {0:0.25, 1:0.5, 2:0.75, 3:1},
    n_instances_per_bag: 9,
    stain: 'pas',
    batch: 5,
    num_workers: 8,
    epochs: 10,
    lr0: 0.0001,
    limit_n_bags_to: 30
  }
##################################################

##################################################
#############    TEST_INFERERS.PY    #############
##################################################
test_yolo_infere_detect_muw_sfog:
  {
    repository_dir: '/Users/marco/yolo/code/helical',
    yolov5dir: '/Users/marco/yolov5',
    images_dir: '/Users/marco/helical_tests/test_cnn_zaneta/detection/tiles/train/images',
    weights: '/Users/marco/yolov5/runs/train/exp139/weights/best.pt',
    save_crop: True,
    augment: False,
    conf_thres: 0.23,
    visualize: False, 
    save_txt: True
  }

test_yolo_infere_detect_hubmap_pas:
  {
    repository_dir: '/Users/marco/yolo/code/helical',
    yolov5dir: '/Users/marco/yolov5',
    images_dir: '/Users/marco/helical_tests/test_yolo_detect_infere_hubmap_pas/test/images',
    weights: '/Users/marco/helical_tests/test_yolo_detect_infere_muw_sfog/best.pt',
    save_crop: True,
    augment: False,
    conf_thres: 0.304,
    visualize: True, 
    save_txt: False
  }


test_inference_tg:
  {
    repository_dir: '/Users/marco/yolo/code/helical',
    yolov5dir: '/Users/marco/yolov5',
    input_dir: '/Users/marco/tg_integration_tests/infere_in',
    output_dir: '/Users/marco/tg_integration_tests/infere_out', 
    save_imgs: True,
    save_txt: True,
    augment: False,
    model: 'yolo',
    mode: 'detection', 
    classify: True,
    device: 'gpu',
    
  }


validate_tg:
  {
    repository_dir: '/Users/marco/yolo/code/helical',
    yolov5dir: '/Users/marco/yolov5',
    input_dir: '/Users/marco/tg_integration_tests/val_in', # should be a folder containing both /images and /labels (labels need to be in yolo format.)
    output_dir: '/Users/marco/tg_integration_tests/val_out', 
    save_imgs: True,
    save_txt: True,
    augment: False,
    model: 'yolo',
    mode: 'detection', 
    classify: True,
    device: 'gpu',
    
  }
##################################################




##################################################
#############    YOLO_PROCESSOR.PY    #############
##################################################
yolo_processor:
  {
    # src_root : '/Users/marco/Downloads/zaneta_files',
    src_root : '/Users/marco/helical_datasets/muw_sfog',
    # src_root : '/Users/marco/Downloads/example_images_zaneta',
    # src_root : '/Users/marco/helical_tests/test_manager_segm_hubmap_pas',
    # src_root : '/Users/marco/helical_tests/test_manager_detect_muw_sfog',
    # dst_root : '/Users/marco/Downloads/example_images_zaneta', 
    dst_root : '/Users/marco/helical_datasets/muw_sfog', 
    # dst_root : '/Users/marco/Downloads/zaneta_files', 
    # dst_root : '/Users/marco/helical_tests/test_manager_segm_hubmap_pas', 
    # dst_root : '/Users/marco/helical_tests/test_manager_detect_muw_sfog', 
    slide_format : 'tif',
    label_format : 'json',
    split_ratio : [0.70, 0.15, 0.15],  
    # data_source : 'zaneta',
    # data_source : 'hubmap',
    data_source : 'muw',
    map_classes: {'Glo-unhealthy':0, 'Glo-NA':1, 'Glo-healthy':2, 'Tissue':3},
    # map_classes: {'Glo-unhealthy':1, 'Glo-healthy':0},
    # map_classes: {'glomerulus':0}, 
    task : 'detection',
    verbose : True,
    safe_copy : False,
    tiling_shape : (2048,2048),
    tiling_step : 1024,
    tiling_level : 2,
    tiling_show : False,
    # stain: 'pas',
    stain: 'sfog',
    multiple_samples: True,
    resize: (512,512),
  }
##################################################

##################################################
#############    YOLO_TRAINER.PY    #############
##################################################
# yolo_trainer:
#   {
#     src_root : '/Users/marco/helical_tests/test_manager_segm_hubmap_pas',
#     # src_root : '/Users/marco/helical_datasets/muw_sfog',
#     dst_root : '/Users/marco/helical_tests/test_manager_segm_hubmap_pas', 
#     # dst_root : '/Users/marco/helical_datasets/muw_sfog',  
#     slide_format : 'tif',
#     label_format : 'json',
#     split_ratio : [0.34, 0.33, 0.33],  
#     # data_source : 'muw',
#     data_source : 'hubmap',
#     task : 'detection',
#     verbose : True,
#     safe_copy : False,
#     tiling_shape : (2048,2048),
#     tiling_step : 1024,
#     tiling_level : 2,
#     tiling_show : True,
#     stain: 'sfog',
#     stain: 'sfog',
#     multiple_samples: True,
#     resize: (512,512),
#   }
# ##################################################