readme: >
  'Best model paths are saved here.' 

yolo: 
  {
  detection:
    { 
      w_classification: 
      # { weights: '/Users/marco/yolov5/runs/train/exp137/weights/best.pt',
      #   conf_thres: 0.425},
      { weights: '/Users/marco/yolov5/runs/train/exp148/weights/best.pt',
        conf_thres: 0.425},
      wo_classification: 
      { weights: '/Users/marco/yolov5/runs/train/exp158/weights/best.pt',
        conf_thres: 0.2}
    },
  
  segmentation:
  }