readme: '- input_dir needs to contain a list of images for detection'

inference:
  augment: false
  classify: true
  device: gpu
  input_dir: /Users/marco/tg_integration_tests/infere_in
  task: detection
  model: yolo
  output_dir: /Users/marco/tg_integration_tests/infere_out
  repository_dir: /Users/marco/yolo/code/helical
  save_imgs: true
  save_txt: true
  yolov5dir: /Users/marco/yolov5
  convert2mask: true
  show_mask: true


validation:
  augment: false
  classify: true
  device: gpu
  input_dir: /Users/marco/tg_integration_tests/val_in
  task: detection
  model: yolo
  output_dir: /Users/marco/tg_integration_tests/val_out
  repository_dir: /Users/marco/yolo/code/helical
  save_txt: true
  yolov5dir: /Users/marco/yolov5
