readme: >
  - input_dir for inference needs to contain a list of images for detection.
  - input_dir for validation needs to be a folder with /images and /labels subfolders. Labels need to be in YOLO format.
  - slides and annotations should be in format <name>_<STAIN>.<format>
  - map classes: {'Cellular Crescent':1, 'Glomerulus':0, 'FibrousCrescent:2'}, {'Glo-unhealthy':0, 'Glo-NA':1, 'Glo-healthy':2, 'Tissue':3},
  - num_workers should be set to 0 for windows gpu

system:
    os: 'macos'

processor: 
  src_root : 'F:\marco\tcd_biopsies' 
  dst_root : 'F:\marco\tcd_biopsies'
  image_type: 'wsi'
  slide_format : 'svs'
  label_format : 'json'
  split_ratio : [0.7, 0.15, 0.15]  
  datasource : 'tcd'
  task : 'detection'
  verbose : True
  safe_copy : False
  tiling_shape: [2048, 2048]
  tiling_step : 512
  tiling_level : 0
  tiling_show : True
  reproducibility: True
  empty_perc: null
  ratio: [0.7,0.2,0.1]
  verbose_level: 'low'
  map_classes: {'Cellular Crescent':1, 'Glomerulus':0, 'FibrousCrescent':2} 
  remove_classes: null
  ignore_classes: [1,2]
  stain: 'pas'
  resize: null #[1024,1024] #[512, 512], # nb non numero singolo!!
  multiple_samples: True
  annotations_in_slide_coords: True # else if in rect coordinates, they need to be rescaled
  testing_mode: True
  add_corners: False # adds corner points in patches were gloms are cropped


yolo_trainer:
  src_root : 'F:\marco\tcd_biopsies'
  dst_root : 'F:\marco\tcd_biopsies'
  repo: 'C:\marco\code\glom_detection\helical'
  yolov5dir: 'C:\marco\yolov5'
  map_classes: {'Cellular Crescent':1, 'Glomerulus':0, 'FibrousCrescent':2} 
  datasource : 'tcd'
  slide_format : 'svs'
  label_format : 'json'
  split_ratio : [0.34, 0.33, 0.33]  
  data_source : 'tcd'
  task : 'detection'
  safe_copy : False
  tiling_shape: [2048, 2048]
  tiling_step : 512
  tiling_level : 0
  tiling_show : True
  stain: 'pas'
  batch_size: 2
  epochs: 10
  save_features: False
  workers: 0
  image_size: 1024
  device: null 
  single_cls: False
  multiple_samples: True
  resize: [640,640]
  yolov5_weights: null # by default yolov5s.pt
  crossvalid_tot_kfolds: 5
  crossvalid_cur_kfold: 2 
  note: 'testing'


inference:
  input_dir: F:\marco\tcd_biopsies/detection/tiles/train/images
  repository_dir:  C:\marco\code\glom_detection\helical
  yolov5dir: C:\marco\yolov5
  augment: false
  classify: false
  device: gpu
  task: detection
  model: yolo
  output_dir: null #
  save_imgs: true
  save_txt: true
  save_crop: true
  create_masks: false
  show_mask: false
  imgsz: [2048,2048]


validation:
  augment: false
  classify: true
  device: gpu
  input_dir: /Users/marco/tg_integration_tests/val_in
  task: detection
  model: yolo
  output_dir: /Users/marco/tg_integration_tests/val_out
  repository_dir: /Users/marco/yolo/code/helical
  save_txt: true
  yolov5dir: /Users/marco/yolov5


yolo_post_processing:
  output_dir: null
  yolov5dir: C:\marco\yolov5
  dst_root: F:\marco\tcd_biopsies
  save_folder: '/Users/marco/helical_tests/test_cropper'
  image_shape: [640,640]
  task: 'detection'
  crop_shape: null
  percentile: null
  plot_boxes: True
  skip_cropped_objects: True


cnn_trainer:
  yolo_data_root: F:\marco\tcd_biopsies\detection
  cnn_data_fold: F:\marco\tcd_biopsies
  map_classes:  {'Glomerulus':0, 'Cellular Crescent':1,  'FibrousCrescent':2} # important that base class (Glomerulus) is 0
  yolo_exp_dir: [ /Users/marco/yolov5/runs/detect/exp60','/Users/marco/yolov5/runs/detect/exp61', '/Users/marco/yolov5/runs/detect/exp62']
  weights_path: C:\Users\hp\.cache\torch\hub\checkpoints\vgg16_bn-6c64b313.pth
  cnn_exp_fold: F:\marco\cnn_runs
  yolov5dir: C:\marco\yolov5
  root_data: F:\marco\tcd_biopsies
  exp_data: C:\marco\yolov5\runs\detect
  lr: 0.001
  k_tot: 4
  k_i: 2
  batch: 7
  epochs: 3
  num_workers: 0
  dataset: 'muw'
  yolo_task: 'detection'
  crop_percentile: 90
  min_w_h: 0.2 # min acceptable size (%) to post process yolo object detection. Default: 0.1
  # resize_crops: false
  resize_shape: [224,224]
  treat_as_single_class: False
  device: 'cpu' # tested for mps and cpu
  skip_test: true
  mutually_exclusive_classes: false