readme: >
  - YOLO imags need to be in a tree like detection -> tiles,wsi -> train,val,test -> images,labels
  - cnn_data_root doesn't need to exist, will be created a tree like: 
    cnn_dataset -> train,val,test -> class0,class1,class2.. ->
  - weights_path: path to the downloaded the VGG16 checkpoint file
  - cnn_exp_fold: desired location to store results from cnn experiments. Doesn't need to exist already.
  - map_classes: this should be the true classes from the detection folder.

  REQUIREMENTS: 
  detect.py in yolo should be changed here: 
    1) for j, (*xyxy, conf, cls) in enumerate(reversed(det)):
    ...
    2) save_one_box(xyxy, imc, file=save_dir / 'crops' / names[c] / f'{p.stem}_crop{j}.jpg', BGR=True)

  to run: 
  (in terminal)
  conda activate success_model
  cd C:\marco\code\glom_detection\helical
  python cnn_trainer.py


#############    CNN_TRAINER.PY    #############
cnn_trainer:
  {
    yolo_data_root: 'D:\marco\test_cnn_trainer2\detection',
    cnn_data_root: 'D:\marco\test_cnn_trainer2',
    yolo_exp_folds: ['D:\marco\test_cnn_trainer2\exp39', 'D:\marco\test_cnn_trainer2\exp40'],
    weights_path: 'C:\Users\hp/.cache\torch\hub\checkpoints\vgg16_bn-6c64b313.pth',
    cnn_exp_fold: 'D:\marco\cnn_model\exps',
    map_classes: {'Glo-healthy':0, 'Glo-unhealthy':1, 'false_positives':2}, 
    lr: 0.00005,
    k_tot: 5,
    k_i: 0,
    # batch: 4,
    epochs: 10,
    num_workers: 0,
    dataset: 'muw',
    task: 'detection',
    resize_crops: True,
    treat_as_single_class: False,
    device: 'cuda:0'
  }
##################################################

#############    CNN FEATURE EXTRACTOR.PY    #############
cnn_feature_extractor:
  {
    cnn_root_fold: 'D:/marco/test_cnn_trainer2',
    map_classes: {'Glo-healthy':0, 'Glo-unhealthy':1, 'false_positives':2},
    vgg_weights_path:  'C:\Users\hp/.cache\torch\hub\checkpoints\vgg16_bn-6c64b313.pth',
    cnn_weights_path: 'D:\marco\test_cnn_trainer2\VGG16_v2-OCT_Retina_half_dataset.pt',
    yolo_root: 'D:/marco/test_cnn_trainer2/detection',
    exp_folds: ['D:/marco/test_cnn_trainer2/exp42', 'D:/marco/test_cnn_trainer2/exp43'],
    batch: 5,
    num_workers: 8,
    resize_crops: True
  }
##################################################

#############    MIL_RUNNER_TRUE.PY    #############
mil_trainer:
  {
    root: 'D:\marco\test_cnn_trainer2\cnn_dataset',
    all_slides_dir: 'D:\marco\test_cnn_trainer2\safe',
    map_classes: {'Glo-healthy':0, 'Glo-unhealthy':1, 'false_positives':2},
    bag_classes:  {0:0.25, 1:0.5, 2:0.75, 3:1},
    n_instances_per_bag: 9,
    stain: 'pas',
    batch: 5,
    num_workers: 8,
    epochs: 10,
    lr0: 0.0001,
    limit_n_bags_to: 30
  }
##################################################

#############    TEST_INFERERS.PY    #############
test_yolo_infere_detect_muw_sfog:
  {
    repository_dir: 'C:\marco\code\glom_detection\helical',
    yolov5dir: 'C:\marco\yolov5',
    images_dir: 'D:\marco\datasets\slides\detection\tiles\test\images',
    weights: 'C:\marco\yolov5\runs\train\exp46\weights\best.pt',
    save_crop: True,
    augment: False,
    conf_thres: 0.575,
    visualize: False, 
    save_txt: True
  }
##################################################


