readme: >
  'Best model paths are saved here.' 

yolo: 
  {
  detection:
    { 
      w_classification: 
      { weights: '',
        conf_thres: 0.425},
      wo_classification: 
      { weights:  C:\marco\yolov5\runs\train\exp5\weights\best.pt,
        conf_thres: 0.35}
    },
  
  segmentation:
  }
